apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-storage
  labels:
    app: api
    component: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
