version: "3.8"

services:
    api:
        build:
            context: .
        image: e-commerce-api
        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./:/var/www/html
            - ./.docker/api/nginx/ssl:/etc/nginx/ssl
            - ./.docker/api/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - postgres-network
        depends_on:
            - postgres
        restart: unless-stopped

    postgres:
        image: postgres:14.1-alpine3.15
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./.docker/postgres/data:/var/lib/postgresql/data
        networks:
            - postgres-network
        restart: unless-stopped

    adminer:
        image: dockette/adminer:pgsql
        ports:
        - 8081:80
        networks:
            - postgres-network
        depends_on:
            - postgres
        restart: unless-stopped

networks:
    postgres-network:
