apiVersion: v1
kind: ReplicationController
metadata:
  name: adminer
  labels:
    app: adminer
    component: database
spec:
  selector:
    app: adminer
    component: database
  template:
    metadata:
      labels:
        app: adminer
        component: database
    spec:
      containers:
        - name: adminer
          image: dockette/adminer:pgsql
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
