apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  labels:
    app: nginx-ingress
    component: ingress
spec:
  type: LoadBalancer
  selector:
    app: nginx-ingress
    component: ingress
  ports:
    - name: http
      port: 80
      nodePort: 30001
    - name: https
      port: 443
      nodePort: 30002
